In [1]:
import numpy as np

a = np.array([1, 0])
b = np.array([0, 1])
print("Vectors :")
print("a = ", a)
print("\nb = ", b)

print("\nCross product of vectors a and b =")
print(np.cross(a, b))

print("------------------------------------")

x = np.array([[2, 6, 9], [2, 7, 3]])
y = np.array([[7, 5, 6], [3, 12, 3]])
print("\nMatrices :")
print("x =", x)
print("\ny =", y)

print("\nCross product of matrices x and y =")
print(np.cross(x, y))

Vectors :
a =  [1 0]

b =  [0 1]

Cross product of vectors a and b =
1
------------------------------------

Matrices :
x = [[2 6 9]
 [2 7 3]]

y = [[ 7  5  6]
 [ 3 12  3]]

Cross product of matrices x and y =
[[ -9  51 -32]
 [-15   3   3]]
