In [1]:
import numpy as np

a = np.array([2, 6])
b = np.array([3, 10])
print("Vectors :")
print("a = ", a)
print("\nb = ", b)

print("\nInner product of vectors a and b =")
print(np.inner(a, b))

print("---------------------------------------")

x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])
print("\nMatrices :")
print("x =", x)
print("\ny =", y)

print("\nInner product of matrices x and y =")
print(np.inner(x, y))


Vectors :
a =  [2 6]

b =  [ 3 10]

Inner product of vectors a and b =
66
---------------------------------------

Matrices :
x = [[2 3 4]
 [3 2 9]]

y = [[ 1  5  0]
 [ 5 10  3]]

Inner product of matrices x and y =
[[17 52]
 [13 62]]
