# INNER PRODUCT

In [1]:
# Python Program illustrating
# numpy.inner() method
import numpy as np

# Vectors
a = np.array([2, 6])
b = np.array([3, 10])
print("Vectors :")
print("a = ", a)
print("\nb = ", b)

# Inner Product of Vectors
print("\nInner product of vectors a and b =")
print(np.inner(a, b))

print("---------------------------------------")

# Matrices
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])
print("\nMatrices :")
print("x =", x)
print("\ny =", y)

# Inner product of matrices
print("\nInner product of matrices x and y =")
print(np.inner(x, y))


Vectors :
a =  [2 6]

b =  [ 3 10]

Inner product of vectors a and b =
66
---------------------------------------

Matrices :
x = [[2 3 4]
 [3 2 9]]

y = [[ 1  5  0]
 [ 5 10  3]]

Inner product of matrices x and y =
[[17 52]
 [13 62]]


# OUTER PRODUCT

In [2]:
# Python Program illustrating
# numpy.outer() method
import numpy as np

# Vectors
a = np.array([2, 6])
b = np.array([3, 10])
print("Vectors :")
print("a = ", a)
print("\nb = ", b)

# Outer product of vectors
print("\nOuter product of vectors a and b =")
print(np.outer(a, b))

print("------------------------------------")

# Matrices
x = np.array([[3, 6, 4], [9, 4, 6]])
y = np.array([[1, 15, 7], [3, 10, 8]])
print("\nMatrices :")
print("x =", x)
print("\ny =", y)

# Outer product of matrices
print("\nOuter product of matrices x and y =")
print(np.outer(x, y))


Vectors :
a =  [2 6]

b =  [ 3 10]

Outer product of vectors a and b =
[[ 6 20]
 [18 60]]
------------------------------------

Matrices :
x = [[3 6 4]
 [9 4 6]]

y = [[ 1 15  7]
 [ 3 10  8]]

Outer product of matrices x and y =
[[  3  45  21   9  30  24]
 [  6  90  42  18  60  48]
 [  4  60  28  12  40  32]
 [  9 135  63  27  90  72]
 [  4  60  28  12  40  32]
 [  6  90  42  18  60  48]]


# CROSS PRODUCT

In [1]:
# Python Program illustrating
# numpy.cross() method
import numpy as np

# Vectors
a = np.array([1, 0])
b = np.array([0, 1])
print("Vectors :")
print("a = ", a)
print("\nb = ", b)

# Cross product of vectors
print("\nCross product of vectors a and b =")
print(np.cross(a, b))

print("------------------------------------")

# Matrices
x = np.array([[2, 6, 9], [2, 7, 3]])
y = np.array([[7, 5, 6], [3, 12, 3]])
print("\nMatrices :")
print("x =", x)
print("\ny =", y)

# Cross product of matrices
print("\nCross product of matrices x and y =")
print(np.cross(x, y))


Vectors :
a =  [1 0]

b =  [0 1]

Cross product of vectors a and b =
1
------------------------------------

Matrices :
x = [[2 6 9]
 [2 7 3]]

y = [[ 7  5  6]
 [ 3 12  3]]

Cross product of matrices x and y =
[[ -9  51 -32]
 [-15   3   3]]


# TENSOR PRODUCT

### |00>

In [7]:
from sympy import Matrix
from sympy.physics.quantum import TensorProduct

ket0 = Matrix([1,0])
ket0 = Matrix([1,0])
TensorProduct(ket0, ket0)


Matrix([
[1],
[0],
[0],
[0]])

### |01>

In [11]:
ket0 = Matrix([1,0])
ket1 = Matrix([0,1])
TensorProduct(ket0, ket1)


Matrix([
[0],
[1],
[0],
[0]])

### |10>

In [12]:
ket1 = Matrix([0,1])
ket0 = Matrix([1,0])

TensorProduct(ket1, ket0)


Matrix([
[0],
[0],
[1],
[0]])

### |11>

In [13]:
ket1 = Matrix([0,1])
ket0 = Matrix([1,0])

TensorProduct(ket1, ket1)

Matrix([
[0],
[0],
[0],
[1]])